# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: ContosoDevExp
metadata:
  name: Contoso
  description: A development box for building and testing Azure Dev CLI
  version: 0.1.0

cloud:
  name: AzureCloud

infra:
  provider: bicep
  path: ./infra/main.bicep
  mode: complete

pipeline:
  provider: github
